FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git curl bash jq 

## Should allow the llm to install required packages

# RUN pip install --no-cache-dir pytest

WORKDIR /workspace
